### ISSUE TITLE
résolution des urls différentes entre le CLI et la tâche grunt

### ISSUE THREAD

**Issue by enguerran** [cssnext/grunt-cssnext#1]
In a file `./vr-ui/src/vr/styleguide/test.css` containing:

```
@font-face {
  font-family: 'GothamRnd';
  src: url("fonts/GothamRnd-Book.otf");
}

html {
  background-image: url("image/wtf.png");
}
```

With a `Gruntfile.js` configured as this:

```
module.exports = function (grunt) {
    require('load-grunt-tasks')(grunt);

    grunt.initConfig({
        cssnext: {
            test: {
                files: {
                    "toto/test.css": "vr-ui/src/vr/styleguide/test.css"
                }
            }
        }
    });
}
```

When running `grunt cssnext:test`, you get the file `./toto/test.css` containing:

```
@font-face {
  font-family: 'GothamRnd';
  src: url("../vr-ui/src/vr/styleguide/fonts/GothamRnd-Book.otf");
}

html {
  background-image: url("../vr-ui/src/vr/styleguide/image/wtf.png");
}
```

But using the CLI `cssnext vr-ui/src/vr/styleguide/test.css toto/test.css`, I get `toto/test.css` containing:

```
@font-face {
  font-family: 'GothamRnd';
  src: url("fonts/GothamRnd-Book.otf");
}

html {
  background-image: url("image/wtf.png");
}
```

**Comment by MoOx** [comment]
First, please use english for issue on a repository that use only english.
Second, for support (because this is more a question than a bug _at first_), please use gitter channel https://gitter.im/cssnext/cssnext

The behavior of this grunt plugin is as expected according to these 2 things:
- http://cssnext.io/usage/#url
- https://github.com/cssnext/grunt-cssnext#options

The behavior of cssnext cli is not correct at the moment, please follow the opened issue to track the resolution https://github.com/cssnext/cssnext/issues/159

**Comment by enguerran** [comment]
Well so it's a bug, but not so much in the grunt-cssnext than in the cssnext CLI. A different behavior is never a good thing.
For those who face the same thing, use the option as below:

``` js
module.exports = function (grunt) {
    require('load-grunt-tasks')(grunt);

    grunt.initConfig({
        cssnext: {
            test: {
                options: {
                    url: false
                },
                files: {
                    "toto/test.css": "vr-ui/src/vr/styleguide/test.css"
                }
            }
        }
    });
}
```

More details, see https://github.com/cssnext/cssnext/blob/master/docs/content/usage.md#url

**Comment by MoOx** [comment]
That why I said "at first" and linked the real (opened) issue for the CLI bug.
I already linked the url option documentation http://cssnext.io/usage/#url :)
